title: "Yang Lab"
email: haofrankyang@jhu.edu
description: "Research at Johns Hopkins University"
url: "https://whocansavemyhair.github.io"   # 改成你的 GitHub 用户名
baseurl: "/web"                 # 如果仓库名是 yourusername.github.io，这里要留空 ""

remote_theme: mmistakes/minimal-mistakes

plugins:
  - jekyll-include-cache

# 禁用默认 sidebar
defaults:
  - scope:
      path: ""
    values:
      sidebar: false

